# Generated by Django 5.1 on 2024-08-30 15:32

import django.core.validators
import django.db.models.deletion
import quran.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aya',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('number', models.IntegerField()),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'Ayat',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=40)),
                ('number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to=quran.models.Reader.imagesave)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aya_Audio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('audio', models.FileField(upload_to=quran.models.Aya_Audio.imagesave)),
                ('aya', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quran.aya')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=40)),
                ('start_page', models.IntegerField(blank=True, null=True)),
                ('end_page', models.IntegerField(blank=True, null=True)),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quran.part')),
            ],
            options={
                'db_table': 'Surah',
            },
        ),
        migrations.AddField(
            model_name='aya',
            name='surah',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quran.surah'),
        ),
    ]
