# Generated by Django 5.1 on 2024-08-30 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_place_rename_name_surah_ar_name_remove_surah_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surah',
            name='number',
            field=models.IntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
